pc-bios/s390-ccw: struct tpi_info must be declared as aligned(4)
Upstream-status: n/a yet (likely later, but downstream fix is required now)

I've run into a compilation error today with the current version of GCC:

In file included from s390-ccw.h:49,
                 from main.c:12:
cio.h:128:1: error: alignment 1 of 'struct tpi_info' is less than 4 [-Werror=packed-not-aligned]
 } __attribute__ ((packed));
 ^
cc1: all warnings being treated as errors

Since the struct tpi_info contains an element ("struct subchannel_id schid")
which is marked as aligned(4), we've got to mark the struct tpi_info as
aligned(4), too.

Signed-off-by: Thomas Huth <thuth@redhat.com>