pc/q35: Disallow vfio-pci hotplug without VT-d caching mode
RH-Author: Peter Xu <peterx@redhat.com>
Message-id: <20191009123947.21505-5-peterx@redhat.com>
Patchwork-id: 91352
O-Subject: [RHEL-8.2.0 qemu-kvm PATCH 4/5] pc/q35: Disallow vfio-pci hotplug without VT-d caching mode
Bugzilla: 1738440
RH-Acked-by: Paolo Bonzini <pbonzini@redhat.com>
RH-Acked-by: Auger Eric <eric.auger@redhat.com>
RH-Acked-by: Alex Williamson <alex.williamson@redhat.com>
Signed-off-by: Danilo C. L. de Paula <ddepaula@redhat.com>

Conflicts:

  hw/i386/pc.c: context differs on quite a few places in
    pc_machine_class_init(), but none of them is really relevant to
    current change.

Instead of bailing out when trying to hotplug a vfio-pci device with
below configuration:

  -device intel-iommu,caching-mode=off

With this we can return a warning message to the user via QMP/HMP and
the VM will continue to work after failing the hotplug:

  (qemu) device_add vfio-pci,bus=root.3,host=05:00.0,id=vfio1
  Error: Device assignment is not allowed without enabling caching-mode=on for Intel IOMMU.

Reviewed-by: Eric Auger <eric.auger@redhat.com>
Signed-off-by: Peter Xu <peterx@redhat.com>
Message-Id: <20190916080718.3299-4-peterx@redhat.com>
Reviewed-by: Michael S. Tsirkin <mst@redhat.com>
Signed-off-by: Michael S. Tsirkin <mst@redhat.com>
(cherry picked from commit c6cbc29d36fe8df078776ed715c37cebac582238)
Signed-off-by: Peter Xu <peterx@redhat.com>